version: '3.1'

services:
  mongo:
    image: mongo:4.4.10
    restart: on-failure
    ports:
      - "27017:27017"
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: anva
      MONGO_INITDB_ROOT_PASSWORD: Welcome1!